# name: GitHub Actions PR CHECKS to CHECK BUILD IMAGE
# # on: 
# #     pull_request_review:
# #       types: [submitted]
# on:
#   # To get Pull Request Comments, you need to be scanning on Pull Request
#   pull_request:
# #     branches: [ "features/dhrj" ]
#     branches:
# #For example, you can restrict actions on pull requests to only run when created against the main branch:
# #ref : https://futurestud.io/tutorials/github-actions-run-on-pull-request
# #       - features/dhrj
# #       - features/dhrj2
# #       - features/GA*
# #       - features/DI*
#       - dev
#       - test
#       - demo
#       - prod
# jobs:

#   PR-Check-Docker-build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v3
#     - name: Declare some variables
#       id: vars
#       shell: bash
#       run: |
#         echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
#     - name: Build docker image
#       shell: bash
#       env:
#         DOCKER_TAG: ${{ steps.vars.outputs.branch }}-${{ steps.vars.outputs.sha_short }}
#         PROJECT_NAME: ${{ github.event.repository.name }}
#         BRANCH_NAME: ${{ steps.vars.outputs.branch }}
#         COMMIT_HASH: ${{ github.sha }}
#         APP_NAME: 'configr'
#         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
#         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_SECRET }}
#       run: |
#           docker build . --file Dockerfile --tag ${APP_NAME}:$GITHUB_REF_NAME




name: GitHub Actions PR CHECKS to CHECK BUILD IMAGE

on:
  # To get Pull Request Comments, you need to be scanning on Pull Request
  pull_request:
    branches:
      - features/*
      - dev
jobs:

  PR-Check-Docker-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Declare some variables
      id: vars
      shell: bash
      run: |
        echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
    - name: Build docker image
      shell: bash
      env:
        DOCKER_TAG: ${{ steps.vars.outputs.branch }}-${{ steps.vars.outputs.sha_short }}
        PROJECT_NAME: ${{ github.event.repository.name }}
        BRANCH_NAME: ${{ steps.vars.outputs.branch }}
        COMMIT_HASH: ${{ github.sha }}
        APP_NAME: 'configr'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_SECRET }}
      run: |
          docker build . --file Dockerfile --tag ${APP_NAME}:$GITHUB_REF_NAME